#@TYPE: Machine
#@NAME: Altera SoCFPGA Agilex3
#@DESCRIPTION: Additional machine configuration for the Agilex3 SoCFPGA

IMAGE_TYPE:agilex3 ?= "gsrd"

UBOOT_CONFIG:agilex3 ?= "agilex3-socdk-atf"

KERNEL_DEVICETREE = " "

64MB_QSPI_BUILD ?= "0"
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS:append:agilex3 = "${@' kernel-modules device-tree hw-ref-design' if d.getVar('64MB_QSPI_BUILD') != '1' else ''}"
EXTRA_IMAGEDEPENDS:append:agilex3 = "${@' u-boot-socfpga-scr' if d.getVar('64MB_QSPI_BUILD') != '1' else ''}"

IMAGE_BOOT_FILES:agilex3 = " \
		boot.scr.uimg \
		u-boot.itb \
		kernel.itb \
		"
HYP_BUILD ?= "0"
XEN_EXTRA_PACKAGES = ""
XEN_EXTRA_PACKAGES:append = "${@'kernel-module-xen-blkback kernel-module-xen-gntalloc kernel-module-xen-gntdev kernel-module-xen-netback kernel-module-xen-wdt xen xen-tools xen-tools-xenstat ' if d.getVar('HYP_BUILD') == '1' else ''}"
IMAGE_INSTALL:append:agilex3 = "${@' socfpga-xen-passthrough' if d.getVar('HYP_BUILD') == '1' else ''}"
IMAGE_BOOT_FILES:append:agilex3 = "${@' xen Image devicetree/socfpga_agilex3_vanilla.dtb boot.scr.xen.uimg agilex3_gsrd_ghrd/ghrd.core.rbf' if d.getVar('HYP_BUILD') == '1' else ''}"

