# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

AGILEX3_QSPI_BUILD ??= "0"
BBFILES:append = "${@bb.utils.contains('AGILEX3_QSPI_BUILD', '1', ' ${LAYERDIR}/recipes-images/poky/core-image-minimal.bbappend', ' \
    ${LAYERDIR}/recipes-connectivity/*/*.bbappend \
    ${LAYERDIR}/recipes-gsrd/socfpga-gsrd*/*.bb \
    ${LAYERDIR}/recipes-gsrd/socfpga-intel*/*.bb \
    ${LAYERDIR}/recipes-gsrd/socfpga-lighttpd*/*.bb \
    ${LAYERDIR}/recipes-connectivity/*/*.bb \
    ${LAYERDIR}/recipes-tools/*/*.bb \
    ${LAYERDIR}/recipes-core/*/*.bb  \
    ${LAYERDIR}/recipes-core/*/*.bbappend \
    ${LAYERDIR}/recipes-images/*/*.bb \
    ${LAYERDIR}/recipes-support/*/*.bb \
    ', d)}"

BBFILES:append = "${@bb.utils.contains('MACHINE', 'arria10', ' ${LAYERDIR}/recipes-support/*/*.bbappend', '', d)}"

# We have a recipes directory, add to BBFILES
BBFILES:append = " ${LAYERDIR}/recipes-bsp/*/*.bb"
BBFILES:append = " ${LAYERDIR}/recipes-bsp/*/*.bbappend"
BBFILES:append = " ${LAYERDIR}/recipes-kernel/*/*.bbappend"
BBFILES:append = " ${LAYERDIR}/recipes-devtools/*/*.bbappend"

# Conditionally include recipes-extended if HYP_BUILD is set to 1
HYP_BUILD ??= "0"

BBFILES:append = "${@bb.utils.contains('HYP_BUILD', '1', ' ${LAYERDIR}/recipes-extended/*/*.bbappend ${LAYERDIR}/recipes-extended/*/*.bb ${LAYERDIR}/recipes-gsrd/socfpga-xen-passthrough/*.bb', '', d)}"

BBFILE_COLLECTIONS:append = " meta-intel-fpga-refdes"
BBFILE_PATTERN_meta-intel-fpga-refdes := "^${LAYERDIR}/"

# Increase the layer priority
BBFILE_PRIORITY_meta-intel-fpga-refdes = "20"

LAYERSERIES_COMPAT_meta-intel-fpga-refdes = "master walnascar"
